development:
  adapter: postgresql
  encoding: unicode
  database: myflix_development
  host: localhost
  pool: 5
  username: jdhang
  password: test 

test:
  adapter: postgresql
  encoding: unicode
  database: myflix_test
  pool: 5
  username: jdhang
  password: test